### Site Settings ###
title               : Camila Salazar
description         : >-
                      I am a Social Data Scientist, analyzing data for social impact.
baseurl             : camilamila.github.io                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
open_new_tab        : true

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md



### Author Info ###
author:
  name              : Camila Salazar
  image             : https://drive.google.com/file/d/1CyCj2bKNxYUIpl6i8zcd7eZxRG4PwQV6/view?usp=sharing
  email             : camila.salazarm@gmail.com
  github            : Camilamila
  linkedin          : camilasalazarm
  twitter           : @milamila07


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name



### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
